server:
  port : 8089
spring : 
  datasource : 
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://49.235.118.172:3306/entertain
    username : root
    password : Ddfh960510@
mybatis :
  mapper-locations : classpath*:/mappers/*.xml
  type-aliases-package : com.dfh.enter.mappers.*
  
