server:
  port : 8089
spring : 
  datasource : 
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/oasys?useUnicode=true&amp;characterEncoding=UTF8?autoReconnect=true
    username : root
    password : 123456
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates



mybatis : 
  mapper-locations : classpath*:/mappers/*.xml
  type-aliases-package : com.dfh.enter.entity
  
